package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/Matnazar-Matnazarov/notes-api-go/internal/config"
	"github.com/Matnazar-Matnazarov/notes-api-go/internal/database"
	"github.com/Matnazar-Matnazarov/notes-api-go/internal/handlers"

	_ "github.com/Matnazar-Matnazarov/notes-api-go/docs" // Swagger docs (generated by: make swagger)
)

// @title           Notes API
// @version         1.0
// @description     Bu loyiha - Notes CRUD backend API. Foydalanuvchilar eslatmalar yaratish, ko'rish, yangilash va o'chirish imkoniyatiga ega.
// @description     Bu API RESTful prinsiplarga asoslangan va PostgreSQL database bilan ishlaydi.

// @contact.name   API Support
// @contact.email  support@example.com

// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT

// @host      localhost:8080
// @BasePath  /api/v1

// @schemes   http https

func main() {
	// Load configuration from environment variables
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("❌ Failed to load configuration: %v", err)
	}

	// Connect to database
	if err := database.Connect(cfg); err != nil {
		log.Fatalf("❌ Failed to connect to database: %v", err)
	}
	defer database.Close()

	// Run database migrations
	if err := database.Migrate(); err != nil {
		log.Fatalf("❌ Failed to run migrations: %v", err)
	}

	// Setup HTTP routes
	router := handlers.SetupRoutes()

	// Start server in a goroutine so we can handle shutdown gracefully
	serverAddr := ":" + cfg.ServerPort
	go func() {
		log.Printf("🚀 Server starting on port %s", cfg.ServerPort)
		log.Printf("📝 API endpoints available at http://localhost%s/api/v1/notes", serverAddr)
		log.Printf("📚 Swagger documentation available at http://localhost%s/swagger/index.html", serverAddr)
		if err := router.Run(serverAddr); err != nil {
			log.Fatalf("❌ Failed to start server: %v", err)
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the server
	// This allows the server to finish processing current requests
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Println("🛑 Shutting down server...")
}
